---
title: "Functions"
author: "Juliette Verstaen"
date: "5/17/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
source("R/auto_power.R")

### generate sample speeds from a distribution
nsample <-  10000
meanspeed <- 100 / 3.6 ### mean speed is 100 km/h
meanspeed_reduced <- 80 / 3.6 ### mean speed is 80 km/h
lowered_croll <- 0.015/2

### generate speeds
speeds <-  rnorm(mean = meanspeed, sd = meanspeed*0.1, n = nsample)
speeds_reduced <- rnorm(mean = meanspeed_reduced, sd = meanspeed*0.1, n = nsample)

### sampling different cars
possible_cars <-  data.frame(mass=c(31000,45000,38000), area = c(25,30,22))

# use model to generate power for the possible cars
possible_cars$power <-  auto_power(v=meanspeed, a = possible_cars$area, m=possible_cars$area)

### define probablity of each car in the world we created where there's only 3 cars!
possible_cars$prob <-  c(0.4, 0.4, 0.2)

summary(speeds)

results <-  data.frame(speed=speeds, speeds_reduced = speeds_reduced)

### assign each car an id
possible_cars$row <-  seq(from=1, to=nrow(possible_cars))

whichcar <-  base::sample(possible_cars$row, size=nsample, prob=possible_cars$prob, replace=TRUE)

### look at the data you generated
head(whichcar)

results$mass <-  possible_cars$mass[whichcar]

head(results)

results$area = possible_cars$area[whichcar]

### get the power for all the cars speeds we generated
### rolling_power uses speeds with mean 100 km/h and the lowered rolling coefficient
results$rolling_power = auto_power(a=results$area, v=results$speed, m=results$mass, c_roll = lowered_croll)

### lower_speed power uses a different set of randomly generated speeds (speeds_reduced) and the normal rolling coefficient

results$lower_speed_power = auto_power(a=results$area, v=results$speeds_reduced, m=results$mass)

summary(results$rolling_power)
summary(results$lower_speed_power)

```

Graphs!!
```{r}

results_graph <- results %>% 
  select(rolling_power, lower_speed_power) %>% 
  gather(key = "Scenario", value = "Power" )

ggplot(results_graph) +
  geom_histogram(aes(x = Power/1000))+
  facet_wrap(~Scenario) +
  theme_classic()

ggplot(results_graph) +
  geom_boxplot(aes(y = Power/1000))+
  facet_wrap(~Scenario) +
  theme_classic()

mean(results$rolling_power)/1000 ### 182.5571 kW reduced resistance
mean(results$lower_speed_power)/1000 ### 178.4378 kW reduced speed

```
```

