---
title: "Assignment 4"
author: "Juliette Verstaen"
date: "5/28/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(magrittr)
```

#### Create Test Data

###Fish Caught 
```{r}

### create vector of possible fish 
possible.fish = c("parrotfish","unicornfish","bonito","yellowfin","swordfish")

###Fish Catch Data (I used long format data frame)###

### number of fish caught on northside
catch_north <- sample(possible.fish, size=20, replace=T) %>%
  as_tibble %>%
  group_by(value) %>%
  count() %>%
  magrittr::set_colnames(value = c("fish", "north"))
  
### number of fish caught on eastside
catch_east <- sample(possible.fish, size=20, replace=T) %>%
  as_tibble %>%
  group_by(value) %>%
  count() %>%
  magrittr::set_colnames(value = c("fish", "east"))

### number of fish caught on westside
catch_west <- sample(possible.fish, size=20, replace=T) %>%
  as_tibble %>%
  group_by(value) %>%
  count() %>%
  magrittr::set_colnames(value = c("fish", "west"))
                       
### combine all together

catch_all_1 <- left_join(catch_north, catch_east, by= "fish")
catch_location_data <- left_join(catch_all_1, catch_west, by= "fish") %>%
  as.tibble() 

as.numeric(catch_location_data$north)

#some runs have NAs instead of zeros from the sample of possible fish. This is in case that happens
catch_location_data[is.na(catch_location_data)] <- 0

```

###Price Data
```{r}

### In Polyneisan Francs
price_data <- c("4000","15000", "20000", "25000", "20000") %>%
  as.tibble %>%
  mutate(fish = c("parrotfish", "unicornfish", "bonito", "yellowfin","swordfish")) %>%
  magrittr::set_colnames(value = c("price", "fish")) %>%
  mutate(price = parse_double(price, na = "0"))

```

####Run Function
```{r}

source("R/calc_fisheries_data.R")

summary <- fish_summary(catch_location_data = catch_location_data, price_data = price_data, graph = TRUE)
summary

```



